spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tbank
    username: tbank
    password: tbank
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
